resource "kubernetes_namespace" "platform" {
  metadata {
    name = var.namespace
    labels = {
      # Pod Security Admission, as taught in W07, enforced at namespace level.
      "pod-security.kubernetes.io/enforce"         = "baseline"
      "pod-security.kubernetes.io/enforce-version" = "latest"
      "pod-security.kubernetes.io/audit"           = "restricted"
      "pod-security.kubernetes.io/audit-version"   = "latest"
      "pod-security.kubernetes.io/warn"            = "restricted"
      "pod-security.kubernetes.io/warn-version"    = "latest"
      "app.kubernetes.io/part-of"                  = "ead-platform"
    }
  }
}

# Credentials are generated by Terraform, never written to the repository.
resource "random_password" "mongodb" {
  length  = 28
  special = false
}

resource "random_password" "rabbitmq" {
  length  = 28
  special = false
}

resource "kubernetes_secret" "mongodb" {
  metadata {
    name      = "mongodb-credentials"
    namespace = kubernetes_namespace.platform.metadata[0].name
  }

  data = {
    username = "eadapp"
    password = random_password.mongodb.result
  }

  type = "Opaque"
}

resource "kubernetes_secret" "rabbitmq" {
  metadata {
    name      = "rabbitmq-credentials"
    namespace = kubernetes_namespace.platform.metadata[0].name
  }

  data = {
    username = "eadapp"
    password = random_password.rabbitmq.result
    # KEDA's RabbitMQ scaler authenticates with a full AMQP URI.
    amqpUri = "amqp://eadapp:${random_password.rabbitmq.result}@rabbitmq.${var.namespace}.svc.cluster.local:5672/"
  }

  type = "Opaque"
}
